version: "3.9"

services:
  helloworld-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helloworld-app
    ports:
      - "3232:3232"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms256m -Xmx512m"
    restart: always
